package com.cdm.sig.models.integrations

enum class ESeccion {
    METALMECANICA,
    BOBINADOS,
    CARPINTERIA,
    RECUPERACIÓN_DE_MATERIALES,
    MEDIDORES,
    ENSAMBLE,
    CONEXIONES,
    DESARME_Y_DESENCUBE,
    LAVADO,
    PINTURA,
    LABORATORIO,
    ALMACEN,
    ADMINISTRATIVO,
    PRODUCCION,
    ENCUBE
}